

listen=YES
local_enable=YES
write_enable=YES
local_umask=022
dirmessage_enable=YES
use_localtime=YES
xferlog_enable=YES
connect_from_port_20=YES
chroot_local_user=YES
secure_chroot_dir=/var/run/vsftpd/empty
pam_service_name=vsftpd
#pasv_address=127.0.0.1
#allow_writeable_chroot=YES
# instead of certificates selfsigned? 
rsa_cert_file=/etc/ssl/certs/ftp-cert.pem
rsa_private_key_file=/etc/ssl/private/ftp-key.pem
ssl_enable=YES
pasv_enable=YES
pasv_min_port=21100
pasv_max_port=21110