
# HTTPS server block for wordpress 
server {
    
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    #server_name poverbec.42.fr;
    server_name ${DOMAIN_NAME}

    # add SSL certificate
    ssl_protocols TLSv1.3;
    ssl_certificate /etc/nginx/certs/certificate.pem;
    ssl_certificate_key /etc/nginx/certs/privKey.pem;

    add_header X-Frame-Options SAMEORIGIN;
    add_header X-Content-Type-Options nosniff;

    # Add location blocks for WordPress
    root /var/www/html;
    index index.php index.html;

    location / {
        try_files $uri $uri/ /index.php?$args;
    }

    location = /paulswebsite {
        return 301 /paulswebsite/;
    }

    location /paulswebsite/ {
        alias /var/www/paulswebsite/;
        index index.html;
        try_files $uri $uri/ /paulswebsite/index.html;
    }

    # ngix passes request of index.php to wp container on port 9000
    location ~ \.php$ {
        fastcgi_pass wordpress:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
    }



}
