#version: "3.8"


#without docker swarm first
services:
  nginx:
    build: ./requirements/nginx/.
    container_name: nginx
    restart: on-failure
    ports:
     - "443:443"
    depends_on:
      - wordpress
    networks:
      - inception
    volumes:
      - ./requirements/nginx/conf:/etc/nginx/conf.d
      - wordpress_data:/var/www/html
      - ../secrets/ssl:/etc/nginx/certs:ro
    secrets:
      - privKey
      - certificate


  wordpress:
    build: ./requirements/WordPress/.
    container_name: wordpress
    volumes:
      - wordpress_data:/var/www/html
    restart: on-failure
    expose:
      - 9000
    env_file:
      - .env
    environment:
      MYSQL_HOST: mariadb
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      WP_ADMIN_USER: ${WP_ADMIN_USER}
      WP_ADMIN_EMAIL: ${WP_ADMIN_EMAIL}
      WP_DB_PREFIX: ${WP_DB_PREFIX}
      WP_USER: ${WP_USER}
      WP_USER_EMAIL: ${WP_USER_EMAIL}
      FTP_USER: ${FTP_USER}
    secrets:
      - wp_admin_password 
      - wp_user_password
      - db_user_password
      - db_root_password
    networks:
      - inception
    depends_on:
      mariadb:
        condition: service_healthy
      redis:
        condition: service_started
  
  redis:
    build:
      context: ./requirements/redisCache
      dockerfile: Dockerfile
    image: redis
    container_name: redis
    restart: on-failure
    networks:
      - inception
  
  FTP_Server:
    build:
      context: ./requirements/ftp_server
      dockerfile: Dockerfile
    image: ftp_server
    container_name: ftp_server
    ports:
      - "21:21"
      - "30000-30009:30000-30009"
    volumes:
      - wordpress_data:/var/www/html
    environment:
      FTP_USER: ${FTP_USER}
    secrets:
      - wp_admin_password
      #- FTPprivKey
      #- FTPcertificate
      - sftp_password
    shm_size: "1gb"
    restart: unless-stopped
    networks:
      - inception
    depends_on:
      - wordpress


  mariadb:
    build: ./requirements/MariaDB/.
    volumes:
      - mariadb_data:/var/lib/mysql
    container_name: mariadb
    restart: on-failure
    expose:
      - 3306
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
    secrets:
      - db_root_password
      - db_user_password
    networks:
      - inception
    healthcheck:
      test: ["CMD-SHELL", "mariadb -u root --password=$(cat /run/secrets/db_root_password) -e 'SELECT 1'"]
      interval: 10s
      timeout: 5s
      retries: 5 
      start_period: 30s

  #portfolio:
  #  build:
  #    context: ./requirements/portfolio
  #    dockerfile: Dockerfile
  #  container_name: portfolio
  #  restart: on-failure
  #  networks:
  #    - inception
      
volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/poverbec/data/mariadb

  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/poverbec/data/wordpress

networks:
  inception: 
    name: inception
    driver: bridge

secrets:
  db_root_password:
    file: ../secrets/db_root_password.txt
  db_user_password:
    file: ../secrets/db_user_password.txt
  wp_admin_password:
    file: ../secrets/wp_admin_password.txt
  wp_user_password:
    file: ../secrets/wp_user_password.txt
  privKey:
    file: ../secrets/ssl/privKey.pem
  certificate:
    file: ../secrets/ssl/certificate.pem
  sftp_password:
    file: ../secrets/sftp_password.txt
  #FTPcertificate:
  #  file: ../secrets/sftpSSL/ftp-cert.pem
  #FTPprivKey:
  #  file: ../secrets/sftpSSL/ftp-key.pem


