#version: "3.8"


#without docker swarm first
services:
  nginx:
    build: ./requirements/nginx/.
    container_name: nginx
    restart: on-failure
    ports:
     - "443:443"
     - "8080:80"
    depends_on:
      - wordpress
    networks:
      - inception
    volumes:
      - ./requirements/nginx/conf:/etc/nginx/conf.d


  wordpress:
    build: ./requirements/WordPress/.
    container_name: wp-php
    restart: on-failure
    ports:
      - "9000:9000"
    env_file:
      - .env
    environment:
      MYSQL_HOST: mariadb
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      WP_ADMIN_USER: ${WP_ADMIN_USER}
      WP_ADMIN_PASSWORD: ${WP_ADMIN_PASSWORD}
      WP_ADMIN_EMAIL: ${WP_ADMIN_EMAIL}
      WP_DB_PREFIX: ${WP_DB_PREFIX}
    networks:
      - inception
    depends_on:
      - mariadb

  mariadb:
    build: ./requirements/MariaDB/.
    container_name: mariadb
    restart: on-failure
    ports:
      - "3306:3306"
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - inception

networks:
  inception:
    driver: bridge

